//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by Gameplay Ability System - Attribute Group Editor
//     version 1
//     from Assets/Gameplay Ability System DOTS/AttributeSystem/PrimaryAttributes.gasattr
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Collections;
using Unity.Jobs;
using Unity.Entities;

namespace MyGameplayAbilitySystem.Attributes
{
    public class PrimaryAttributeCurrentValueUpdateSystem : SystemBase
    {
        protected override void OnUpdate()
        {
            
        this.Dependency = Entities.ForEach(
            (ref AttributeStrength.CurrentValue currentValue, in AttributeStrength.Modifier modifier, in AttributeStrength.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeIntelligence.CurrentValue currentValue, in AttributeIntelligence.Modifier modifier, in AttributeIntelligence.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeAgility.CurrentValue currentValue, in AttributeAgility.Modifier modifier, in AttributeAgility.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeMaxHealth.CurrentValue currentValue, in AttributeMaxHealth.Modifier modifier, in AttributeMaxHealth.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeHealth.CurrentValue currentValue, in AttributeHealth.Modifier modifier, in AttributeHealth.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeMaxMana.CurrentValue currentValue, in AttributeMaxMana.Modifier modifier, in AttributeMaxMana.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);


        this.Dependency = Entities.ForEach(
            (ref AttributeMana.CurrentValue currentValue, in AttributeMana.Modifier modifier, in AttributeMana.BaseValue baseValue) =>
            {
                currentValue.Value = (int) (baseValue.Value + modifier.Add + (baseValue.Value * modifier.Multiply));
            }).ScheduleParallel(this.Dependency);

        }
    }
}