//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by Gameplay Ability System - Attribute Group Editor
//     version 1
//     from Assets/Gameplay Ability System DOTS/AttributeSystem/test.attributegroup
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGameplayAbilitySystem.Attributes
{
        /// <summary>
    /// Primary attribute group
    /// </summary>
    public sealed class AttributeGroupPrimary : GameplayAbilitySystem.AttributeSystem.IAttributeGroup
    {
        
        /// <summary>
        /// The character's strength
        /// </summary>
        public sealed class AttributeStrength : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The character's agility
        /// </summary>
        public sealed class AttributeAgility : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The character's intelligence
        /// </summary>
        public sealed class AttributeIntelligence : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The amount of damage player can take
        /// </summary>
        public sealed class AttributeHealth : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The maximum health the player can have
        /// </summary>
        public sealed class AttributeMaxHealth : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The amount of mana the player can use to cast spell.
        /// </summary>
        public sealed class AttributeMana : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }


        /// <summary>
        /// The maximum mana the player can have
        /// </summary>
        public sealed class AttributeMaxMana : GameplayAbilitySystem.AttributeSystem.IAttribute
        {

            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }

            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public short Add;

                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public short Multiply;

                /// <summary>
                /// Value of component
                /// </summary>
                public int Value;
            }
        }

    }
}