//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGameplayAbilitySystem.Attributes
{
    using GameplayAbilitySystem.AttributeSystem;
    
    
    /// <summary>
    /// Primary attribute group
    /// </summary>
    public sealed class AttributeGroupPrimary
    {
        
        /// <summary>
        /// The a mount of damage player can take.
        /// </summary>
        public sealed class AttributeHealth
        {
            
            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Value of component
                /// </summary>
                public float Value;
            }
            
            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Value of component
                /// </summary>
                public float Value;
            }
            
            /// <summary>
            /// Current Modifiers on Attribute
            /// </summary>
            public struct ModifierValues : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public float Add;
                
                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public float Multiply;
            }
        }
        
        /// <summary>
        /// The maximum health the player can have
        /// </summary>
        public sealed class AttributeMaxHealth
        {
            
            /// <summary>
            /// Base Value of Attribute
            /// </summary>
            public struct BaseValue : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Value of component
                /// </summary>
                public float Value;
            }
            
            /// <summary>
            /// Current Value of Attribute
            /// </summary>
            public struct CurrentValue : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Value of component
                /// </summary>
                public float Value;
            }
            
            /// <summary>
            /// Current Modifiers on Attribute
            /// </summary>
            public struct ModifierValues : Unity.Entities.IComponentData
            {
                
                /// <summary>
                /// Total additive modifiers
                /// </summary>
                public float Add;
                
                /// <summary>
                /// Total multiplicative modifiers
                /// </summary>
                public float Multiply;
            }
        }
    }
}
