internal class AttributeGroupCodeGenStrings
{
    public static string HeaderString(int version, string sourceFileName)
    {
        return "//------------------------------------------------------------------------------\n"
                            + "// <auto-generated>\n"
                            + $"//     This code was auto-generated by Gameplay Ability System - Attribute Group Editor\n"
                            + $"//     version {version}\n"
                            + (string.IsNullOrEmpty(sourceFileName) ? "" : $"//     from {sourceFileName}\n")
                            + "//\n"
                            + "//     Changes to this file may cause incorrect behavior and will be lost if\n"
                            + "//     the code is regenerated.\n"
                            + "// </auto-generated>\n"
                            + "//------------------------------------------------------------------------------\n";
    }

    public static string Usings()
    {
        return @"
using GameplayAbilitySystem.AttributeSystem;
using Unity.Entities;
";
    }

    public static string AttributeClass(string attributeName)
    {
        return @"
    public class Attribute{AttributeName}: IAttribute
    {
        public struct BaseValue : IComponentData
        {
            public float Value;
            public static implicit operator float(BaseValue e)
            {
                return e.Value;
            }
        }

        public struct Modifier : IComponentData
        {
            public float Add;
            public float Multiply;
        }

        public struct CurrentValue : IComponentData
        {
            public float Value;
            public static implicit operator float(CurrentValue e)
            {
                return e.Value;
            }
        }
    }        
        ".Replace("{AttributeName}", attributeName);
    }

}